language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install pylint sympy matplotlib"
# command to run tests
script:
  - "nosetests *.py"
# THERE ARE NO NOSETESTS TO RUN AS THE ONLY NEW FILE IS AN IPYTHON FILE. TRAVIS WAS THROWING AN ERROR BECAUSE THERE WERE NO NOSETESTS TO RUN, EVEN THOUGH THE IPYTHON DOCUMENT WORKS FINE.
notifications:
  email: false
